# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Address1', models.CharField(blank=True, max_length=200, null=True)),
                ('Address2', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Zip', models.CharField(blank=True, max_length=200, null=True)),
                ('LastUpdated', models.DateTimeField(default=datetime.datetime(2017, 2, 4, 22, 37, 21, 16800, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='FirstName', max_length=200)),
                ('LastName', models.CharField(default='LastName', max_length=200)),
                ('Hand', models.CharField(default='Hand', max_length=200)),
                ('YearStarted', models.IntegerField(null=True)),
                ('Gender', models.CharField(blank=True, max_length=200, null=True)),
                ('LastUpdated', models.DateTimeField()),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RockLocalID', models.CharField(max_length=200)),
                ('Color', models.CharField(max_length=200)),
                ('Diameter', models.FloatField(default=292.1)),
                ('LastUpdated', models.DateTimeField()),
                ('Club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curling.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initiated', models.DateTimeField(default=datetime.datetime(2017, 2, 4, 22, 37, 21, 30340, tzinfo=utc))),
                ('Club', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='curling.Club')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(blank=True, max_length=200, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Person')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(blank=True, max_length=200, null=True)),
                ('Rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Rock')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SheetLocalID', models.FloatField(blank=True, max_length=200, null=True)),
                ('Width', models.FloatField(default=150)),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeeTripMasterTime', models.DateTimeField(null=True)),
                ('HogTripMasterTime', models.DateTimeField(null=True)),
                ('TeeTripDuration', models.IntegerField(null=True)),
                ('HogTripDuration', models.IntegerField(null=True)),
                ('TempC', models.FloatField(null=True)),
                ('Humidity', models.FloatField(null=True)),
                ('TeePingTime', models.IntegerField(null=True)),
                ('TeeDistance', models.FloatField(null=True)),
                ('HogPingTime1', models.IntegerField(null=True)),
                ('HogPingTime2', models.IntegerField(null=True)),
                ('HogDistance1', models.FloatField(null=True)),
                ('HogDistance2', models.FloatField(null=True)),
                ('BroomPingTime', models.IntegerField(null=True)),
                ('BroomDistance', models.FloatField(null=True)),
                ('BroomInputMethod', models.FloatField(blank=True, max_length=200, null=True)),
                ('Person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curling.Person')),
                ('Rock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curling.Rock')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Session')),
            ],
        ),
        migrations.AddField(
            model_name='rock',
            name='Sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Sheet'),
        ),
    ]
