# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='IsClosed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 23, 7, 15, 980002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='Initiated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 23, 7, 15, 993696, tzinfo=utc)),
        ),
    ]
