# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0002_auto_20170204_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='IsComplete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 23, 8, 57, 522156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='Initiated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 23, 8, 57, 535319, tzinfo=utc)),
        ),
    ]
