# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0003_auto_20170204_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFIDValue', models.CharField(max_length=20)),
                ('LastUpdated', models.DateTimeField(default=datetime.datetime(2017, 2, 5, 21, 46, 45, 499710, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 21, 46, 45, 470522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 21, 46, 45, 477243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rock',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 21, 46, 45, 480841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='Initiated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 5, 21, 46, 45, 483764, tzinfo=utc)),
        ),
    ]
