# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0005_auto_20170205_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 23, 36, 12, 162256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 23, 36, 12, 169582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rfidrawdata',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 23, 36, 12, 193074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rock',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 23, 36, 12, 173256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='Initiated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 23, 36, 12, 176747, tzinfo=utc)),
        ),
    ]
