# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0007_auto_20170209_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='IsSetup',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 19, 28, 20, 76854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 19, 28, 20, 83830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rfidrawdata',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 19, 28, 20, 107512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rock',
            name='LastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 19, 28, 20, 87824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='Initiated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 19, 28, 20, 90869, tzinfo=utc)),
        ),
    ]
