# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0011_auto_20170212_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rock',
            name='Club',
        ),
    ]
