# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0012_remove_rock_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='AvgSplitSpeed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='HogSpeed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='TeeSpeed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='Width',
            field=models.FloatField(default=426.72),
        ),
    ]
