# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0013_auto_20170212_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='NumberOfSheets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
