# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curling', '0014_club_numberofsheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='Hand',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1),
        ),
    ]
